spring:  profiles:    active: qa    
---
spring:
  profiles: dev
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
welcome:
  message: Welcome to my site !

---
spring:
  profiles: qa
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
welcome:
  message: Welcome to my site !  

---
spring:
  profiles: prod
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
welcome:
  message: Welcome to my site !

  